//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HollyWood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDetail
    {
        public long EventDetailID { get; set; }
        public Nullable<long> FK_EventID { get; set; }
        public Nullable<short> FK_EventDelailSatusID { get; set; }
        public string EventDetailName { get; set; }
        public Nullable<short> EventDetailNumber { get; set; }
        public Nullable<decimal> EventDetailOdd { get; set; }
        public string EventDateTime { get; set; }
        public string EventEndDateTime { get; set; }
        public Nullable<short> FinishingPosition { get; set; }
        public Nullable<bool> FirstTimer { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
