//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HollyWood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public long EventID { get; set; }
        public long FK_TounamentID { get; set; }
        public string EventName { get; set; }
        public short EventNumber { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public System.DateTime EventEndDateTime { get; set; }
        public bool AutoClose { get; set; }
    
        public virtual EventDetail EventDetail { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
