//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HollyWood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        public long TournamentID { get; set; }
        public string TournamentName { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
